/****
 * BADGES TYPES
 */
export const UPDATE_LIKE_NOTIFY = 'UPDATE_LIKE_NOTIFY';
export const UPDATE_NOTIFICATION_NOTIFY = 'UPDATE_NOTIFICATION_NOTIFY';
export const RESET_NOTIFY = 'RESET_NOTIFY';

/**
 * USERS REDUCER CASES
 */
export const LOAD_USERS_IMAGES = 'LOAD_USERS_IMAGES';
export const SUCCESS_LOADED_USERS = 'SUCCESS_LOADED_USERS';
export const FAILED_LOADED_USERS = 'FAILED_LOADED_USERS';

/***
 * AppState Reducer Cases
 */
export const APP_STATE_STATUS = 'APP_STATE_STATUS';

/***
 * Notification Action Cases
 */
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const CLEAR_NOTFICATIONS = 'CLEAR_NOTFICATIONS';
